language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_bb7fd5d8e773_key -iv $encrypted_bb7fd5d8e773_iv -in secrets.tar.enc -out secrets.tar -d
  - tar -xvf secrets.tar --overwrite
  - chmod +x gradlew
script:
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then ./gradlew build; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew publish; fi
before_deploy:
  - export RELEASE_CHANGELOG=$(cat app/src/main/play/release-notes/en-US/default.txt | sed 's/'\n'/\'\\n'/')
  - export RELEASE_VERSION=$(./gradlew -q :app:printVersionName)
deploy:
  - provider: releases
    skip_cleanup: true
    overwrite: true
    name: "$RELEASE_VERSION"
    tag_name: "$RELEASE_VERSION"
    body: "$RELEASE_CHANGELOG"
    prerelease: true
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: app/build/outputs/apk/release/*
    on:
      repo: fennifith/Alarmio
      branch: master
